import type { Metadata } from "next";
import { Inter,Josefin_Sans } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "@/components/smooth-scrolling";

const inter = Inter({ subsets: ["latin"] });

const Jose = Josefin_Sans({weight: ["100" ,"200" ,"300" ,"400","500","600" ,"700"], subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Minh Nguyen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SmoothScrolling>
        <body className={Jose.className}>{children}</body>
      </SmoothScrolling>
    </html>
  );
}
